stages:
    - run

Run Benchmark:
    stage: run
    tags:
        - zebrain
    script:
        - docker-compose up locator_benchmark
    when: manual
    
Run Viz:
    stage: run
    tags:
        - preprod3
    script:
        - docker-compose up viz
    when: manual

