stages:
    - run

Run Benchmark:
    stage: run
    tags:
        - zebrain
    script:
        - docker-compose up -d locator_benchmark
    when: manual
    
Run Viz PreProd:
    stage: run
    tags:
        - preprod3
    script:
        - docker-compose down
        - docker-compose up -d --build viz
    when: manual

Run Viz Prod:
    stage: run
    tags:
        - marketanalyis
    script:
        - docker-compose down
        - docker-compose up -d --build viz
    when: manual

