variables:
    DOTNET_IMAGE: mcr.microsoft.com/dotnet/sdk
    WEB_SERVICE_NAME: wehave_api
    PUBLISH_BAGET: http://baget.amarislab.com:5000/v3/index.json

stages:
    - run

Publish Tree-Matching:
    image: $DOTNET_IMAGE
    stage: run
    tags:
        - docker
    before_script:
        - cd tree-matching-csharp
        - dotnet restore
    script:
        - dotnet pack tree-matching-csharp.csproj -c Release -o ./nuget
        - dotnet nuget push -s $PUBLISH_BAGET ./nuget/tree-matching-csharp.*.nupkg
    when: manual

Run Benchmark:
    stage: run
    tags:
        - zebrain
    script:
        - docker-compose up -d --build locator_benchmark
    when: manual
    
Run Viz PreProd:
    stage: run
    tags:
        - preprod3
    script:
        - docker-compose down
        - docker-compose up -d --build viz
    when: manual

Run Viz Prod:
    stage: run
    tags:
        - tools2
    script:
        - docker-compose down
        - docker-compose up -d --build viz
    when: manual

