version: '3'
services:
  locator_benchmark:
    build: 
      context: .
      dockerfile: tree-matching-csharp.Benchmark/Dockerfile
  viz:
    build: 
      context: .
      dockerfile: tree-matching-csharp.Visualization/Dockerfile
    ports:
    - "14530:4678"